### ISSUE TITLE
Failure on Chef 11.4.0

### ISSUE THREAD

**Issue by karmi** [bryanwb/chef-ark#35]
On a recent Chef, the `ark` resources are failing:

```

[2013-02-13T20:25:21+00:00] INFO: *** Chef 11.4.0 ***
[2013-02-13T20:25:21+00:00] DEBUG: Loading cookbook ark's library file: /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb
[2013-02-13T20:25:21+00:00] DEBUG: filtered backtrace of compile error: /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:25:in `<class:Resource>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:24:in `<class:Chef>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:23:in `<top (required)>'
[2013-02-13T20:25:21+00:00] DEBUG: filtered backtrace of compile error: /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:25:in `<class:Resource>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:24:in `<class:Chef>',/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:23:in `<top (required)>'
[2013-02-13T20:25:21+00:00] DEBUG: backtrace entry for compile error: '/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>''
[2013-02-13T20:25:21+00:00] DEBUG: Line number of compile error: '37'

================================================================================
Recipe Compile Error in /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb
================================================================================


NoMethodError
-------------

undefined method `attribute' for Chef::Resource::Ark:Class


Cookbook Trace:
---------------
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:25:in `<class:Resource>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:24:in `<class:Chef>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:23:in `<top (required)>'


Relevant File Content:
----------------------
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:

 30:          @allowed_actions.push(:install, :dump, :cherry_pick, :put, :install_with_make, :configure, :setup_py)
 31:          @action = :install
 32:          @provider = Chef::Provider::Ark
 33:        end
 34:  
 35:        attr_accessor :path, :release_file, :prefix_bin, :prefix_root, :home_dir, :extension, :version
 36:  
 37>>       attribute :owner, :kind_of => String, :default => 'root'
 38:        attribute :group, :kind_of => [String, Fixnum], :default => 0
 39:        attribute :url, :kind_of => String, :required => true
 40:        attribute :path, :kind_of => String, :default => nil
 41:        attribute :full_path, :kind_of => String, :default => nil
 42:        attribute :append_env_path, :kind_of => [TrueClass, FalseClass], :default => false
 43:        attribute :checksum, :regex => /^[a-zA-Z0-9]{64}$/, :default => nil
 44:        attribute :has_binaries, :kind_of => Array, :default => []
 45:        attribute :creates, :kind_of => String, :default => nil
 46:        attribute :release_file, :kind_of => String, :default => ''



[2013-02-13T20:25:22+00:00] DEBUG: Re-raising exception: NoMethodError - undefined method `attribute' for Chef::Resource::Ark:Class
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:25:in `<class:Resource>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:24:in `<class:Chef>'
  /etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:23:in `<top (required)>'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:179:in `load'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:179:in `block in load_libraries_from_cookbook'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:176:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:176:in `load_libraries_from_cookbook'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:98:in `block in compile_libraries'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:97:in `each'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:97:in `compile_libraries'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:70:in `compile'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context.rb:86:in `load'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:224:in `setup_run_context'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:467:in `do_run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:200:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:190:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:239:in `block in run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `loop'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:73:in `run'
  /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/bin/chef-solo:25:in `<top (required)>'
  /usr/bin/chef-solo:23:in `load'
  /usr/bin/chef-solo:23:in `<main>'
[2013-02-13T20:25:22+00:00] ERROR: Running exception handlers
[2013-02-13T20:25:22+00:00] ERROR: Exception handlers complete
[2013-02-13T20:25:22+00:00] FATAL: Stacktrace dumped to /etc/vagrant-chef/chef-stacktrace.out
[2013-02-13T20:25:22+00:00] DEBUG: NoMethodError: undefined method `attribute' for Chef::Resource::Ark:Class
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:37:in `<class:Ark>'
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:25:in `<class:Resource>'
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:24:in `<class:Chef>'
/etc/vagrant-chef/chef-solo-1/cookbooks/ark/libraries/resource_ark.rb:23:in `<top (required)>'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:179:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:179:in `block in load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:176:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:176:in `load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:98:in `block in compile_libraries'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:97:in `compile_libraries'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compiler.rb:70:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context.rb:86:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:224:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:467:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:200:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:190:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:239:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/solo.rb:231:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:73:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:23:in `load'
/usr/bin/chef-solo:23:in `<main>'
[2013-02-13T20:25:22+00:00] FATAL: NoMethodError: undefined method `attribute' for Chef::Resource::Ark:Class
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

This is quite a bit of an issue for the elasticsearch/cookbook-elasticsearch cookbook...

**Comment by halcyonCorsair** [comment]
@bryanwb @karmi 
I ran into the issue and have a pull request on opscode's version of the cookbook here:
https://github.com/opscode-cookbooks/ark/pull/8

**Comment by bryanwb** [comment]
nice work @halcyonCorsair ! l have to test this out now to see if I can pull in all your changes to my branch

**Comment by halcyonCorsair** [comment]
If I recall, there is a failing test in there that comes from the opscode cookbook, but it was non-critical so I left it.

**Comment by bryanwb** [comment]
fixed in https://github.com/bryanwb/chef-ark/commit/991613ebcb4fbb3e0fd5f22863bd1110b027d7fe

tks @halcyonCorsair !

**Comment by karmi** [comment]
Very cool, thanks guys!
